select
    cast(order_date as date) as order_date,
    cast(orders as bigint) as orders,
    cast(orders_with_completion_timestamp as bigint) as orders_with_completion_timestamp,
    cast(orders_with_cancellation_timestamp as bigint) as orders_with_cancellation_timestamp,
    cast(orders_with_both_timestamps as bigint) as orders_with_both_timestamps,
    cast(late_preparation_orders as bigint) as late_preparation_orders,
    cast(items_count as decimal(14, 2)) as items_count,
    cast(sales_revenue_brl as decimal(14, 2)) as sales_revenue_brl,
    cast(shop_revenue_brl as decimal(14, 2)) as shop_revenue_brl,
    cast(offer_expenses_brl as decimal(14, 2)) as offer_expenses_brl,
    cast(commission_expense_brl as decimal(14, 2)) as commission_expense_brl,
    cast(payment_channel_fee_brl as decimal(14, 2)) as payment_channel_fee_brl,
    cast(platform_rewards_brl as decimal(14, 2)) as platform_rewards_brl,
    cast(original_delivery_fee_brl as decimal(14, 2)) as original_delivery_fee_brl,
    cast(new_customer_delivery_fee_brl as decimal(14, 2)) as new_customer_delivery_fee_brl,
    cast(refund_brl as decimal(14, 2)) as refund_brl,
    cast(free_delivery_net_cost_brl as decimal(14, 2)) as free_delivery_net_cost_brl,
    cast(logistics_cost_brl as decimal(14, 2)) as logistics_cost_brl,
    cast(rating_count as bigint) as rating_count,
    cast(rating_sum as decimal(14, 2)) as rating_sum,
    cast(prep_minutes_sum as decimal(14, 2)) as prep_minutes_sum,
    cast(prep_minutes_count as bigint) as prep_minutes_count,
    cast(acceptance_seconds_sum as decimal(14, 2)) as acceptance_seconds_sum,
    cast(acceptance_seconds_count as bigint) as acceptance_seconds_count,
    cast(finalization_seconds_sum as decimal(14, 2)) as finalization_seconds_sum,
    cast(finalization_seconds_count as bigint) as finalization_seconds_count,
    cast(delivery_seconds_sum as decimal(14, 2)) as delivery_seconds_sum,
    cast(delivery_seconds_count as bigint) as delivery_seconds_count
from {{ local_parquet('food99_daily.parquet') }}
