[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#20745B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F4"
textColor = "#17372D"
font = "sans serif"
